name: Pull Request checks

on:
  pull_request:
    # Note: each of these paths requires an ignored path entry in pull_request.yml
    paths:
       - "**.md"
       - ".github/CODEOWNERS"
       - ".github/PULL_REQUEST_TEMPLATE.md"
       - ".editorconfig"
  push:
    branches:
    - main

jobs:
  lint:
    name: 🕵️‍♀️ NPM lint
    runs-on: ubuntu-latest
    steps:
    - run: exit 0

  build_backend:
    name: 🏗 Build backend dev image for tests
    runs-on: ubuntu-latest
    steps:
    - run: exit 0

  check_perl:
    name: 🐪 Check Perl
    needs: [build_backend]
    runs-on: ubuntu-latest
    steps:
    - run: exit 0

  tests:
    name: 🐪 Perl unit tests
    needs: [build_backend]
    runs-on: ubuntu-latest
    steps:
    - run: exit 0

  tests_dev:
    name: 🧪 Test make dev
    needs: [build_backend]
    runs-on: ubuntu-latest
    steps:
    - run: exit 0

  test_deployment:
    name: 🦾 Some test of deployment tools
    runs-on: ubuntu-latest
    steps:
    - run: exit 0
